import 'dotenv/config'
import pg from 'pg'

const { Pool } = pg
let pool

const getPool = () => {
  if (pool) return pool
  const connectionString = process.env.DATABASE_URL
  if (!connectionString) {
    throw new Error('DATABASE_URL is required. Add it to .env locally or connect a Render PostgreSQL database.')
  }

  const isLocalPostgres = /@(localhost|127\.0\.0\.1)(:|\/)/.test(connectionString)
  pool = new Pool({
    connectionString,
    max: 5,
    ssl: process.env.PGSSLMODE === 'require' || (!isLocalPostgres && process.env.NODE_ENV === 'production')
      ? { rejectUnauthorized: false }
      : undefined,
  })
  return pool
}

export const query = (sql, params = []) => getPool().query(sql, params)

export const withTransaction = async (work) => {
  const client = await getPool().connect()
  try {
    await client.query('BEGIN')
    const result = await work(client)
    await client.query('COMMIT')
    return result
  } catch (error) {
    await client.query('ROLLBACK')
    throw error
  } finally {
    client.release()
  }
}

export const initDb = async () => {
  await query(`
    CREATE TABLE IF NOT EXISTS agencies (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL UNIQUE,
      email TEXT NOT NULL,
      phone TEXT,
      website TEXT,
      description TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS universities (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL UNIQUE,
      city TEXT NOT NULL,
      city_safety TEXT NOT NULL DEFAULT 'not_rated',
      city_safety_description TEXT NOT NULL DEFAULT '',
      region TEXT NOT NULL,
      ranking INTEGER,
      ranking_world INTEGER,
      has_csc_scholarship BOOLEAN NOT NULL DEFAULT FALSE,
      specialties TEXT NOT NULL DEFAULT '',
      requirements TEXT NOT NULL DEFAULT '',
      tuition TEXT NOT NULL DEFAULT '',
      description TEXT NOT NULL DEFAULT '',
      website TEXT,
      source_url TEXT,
      verified_at DATE,
      name_translations JSONB NOT NULL DEFAULT '{}'::jsonb,
      description_translations JSONB NOT NULL DEFAULT '{}'::jsonb,
      specialties_translations JSONB NOT NULL DEFAULT '{}'::jsonb,
      requirements_translations JSONB NOT NULL DEFAULT '{}'::jsonb,
      tuition_translations JSONB NOT NULL DEFAULT '{}'::jsonb,
      image_url TEXT,
      image_source TEXT,
      image_gallery JSONB NOT NULL DEFAULT '[]'::jsonb,
      data_status TEXT NOT NULL DEFAULT 'requires_verification',
      data_checked_at DATE,
      agency_id BIGINT REFERENCES agencies(id),
      students_count INTEGER NOT NULL DEFAULT 0,
      province TEXT NOT NULL DEFAULT '',
      founded_year INTEGER,
      campus_area_ha NUMERIC,
      campuses JSONB NOT NULL DEFAULT '[]'::jsonb,
      dorm JSONB NOT NULL DEFAULT '{}'::jsonb,
      campus_facilities JSONB NOT NULL DEFAULT '[]'::jsonb,
      site_rating NUMERIC,
      nearby_cities JSONB NOT NULL DEFAULT '[]'::jsonb,
      nearby_places JSONB NOT NULL DEFAULT '[]'::jsonb,
      climate JSONB NOT NULL DEFAULT '{}'::jsonb,
      international_students INTEGER,
      known_for_translations JSONB NOT NULL DEFAULT '{}'::jsonb,
      living_cost JSONB NOT NULL DEFAULT '{}'::jsonb,
      languages JSONB NOT NULL DEFAULT '[]'::jsonb,
      extra_documents JSONB NOT NULL DEFAULT '[]'::jsonb,
      deadlines JSONB NOT NULL DEFAULT '{}'::jsonb,
      university_grants JSONB NOT NULL DEFAULT '[]'::jsonb,
      province_grant JSONB NOT NULL DEFAULT '{}'::jsonb
    );

    ALTER TABLE universities ADD COLUMN IF NOT EXISTS name_translations JSONB NOT NULL DEFAULT '{}'::jsonb;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS city_safety TEXT NOT NULL DEFAULT 'not_rated';
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS city_safety_description TEXT NOT NULL DEFAULT '';
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS description_translations JSONB NOT NULL DEFAULT '{}'::jsonb;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS specialties_translations JSONB NOT NULL DEFAULT '{}'::jsonb;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS requirements_translations JSONB NOT NULL DEFAULT '{}'::jsonb;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS tuition_translations JSONB NOT NULL DEFAULT '{}'::jsonb;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS image_url TEXT;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS image_source TEXT;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS image_gallery JSONB NOT NULL DEFAULT '[]'::jsonb;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS data_status TEXT NOT NULL DEFAULT 'requires_verification';
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS data_checked_at DATE;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS ranking_world INTEGER;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS has_csc_scholarship BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS province TEXT NOT NULL DEFAULT '';
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS founded_year INTEGER;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS campus_area_ha NUMERIC;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS campuses JSONB NOT NULL DEFAULT '[]'::jsonb;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS dorm JSONB NOT NULL DEFAULT '{}'::jsonb;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS campus_facilities JSONB NOT NULL DEFAULT '[]'::jsonb;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS site_rating NUMERIC;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS nearby_cities JSONB NOT NULL DEFAULT '[]'::jsonb;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS nearby_places JSONB NOT NULL DEFAULT '[]'::jsonb;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS climate JSONB NOT NULL DEFAULT '{}'::jsonb;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS international_students INTEGER;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS known_for_translations JSONB NOT NULL DEFAULT '{}'::jsonb;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS living_cost JSONB NOT NULL DEFAULT '{}'::jsonb;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS languages JSONB NOT NULL DEFAULT '[]'::jsonb;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS extra_documents JSONB NOT NULL DEFAULT '[]'::jsonb;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS deadlines JSONB NOT NULL DEFAULT '{}'::jsonb;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS university_grants JSONB NOT NULL DEFAULT '[]'::jsonb;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS province_grant JSONB NOT NULL DEFAULT '{}'::jsonb;

    CREATE TABLE IF NOT EXISTS users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email TEXT NOT NULL UNIQUE,
      password_hash TEXT,
      google_id TEXT UNIQUE,
      full_name TEXT,
      country TEXT,
      phone TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    ALTER TABLE users ADD COLUMN IF NOT EXISTS google_id TEXT;
    ALTER TABLE users ALTER COLUMN password_hash DROP NOT NULL;
    CREATE UNIQUE INDEX IF NOT EXISTS users_google_id_idx ON users(google_id) WHERE google_id IS NOT NULL;

    CREATE TABLE IF NOT EXISTS auth_sessions (
      token_hash TEXT PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      expires_at TIMESTAMPTZ NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE INDEX IF NOT EXISTS auth_sessions_expires_idx ON auth_sessions(expires_at);

    CREATE TABLE IF NOT EXISTS applications (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES users(id),
      university_id BIGINT NOT NULL REFERENCES universities(id),
      status TEXT NOT NULL DEFAULT 'pending',
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      UNIQUE (user_id, university_id)
    );

    -- Отзывы показываются на карточке только после проверки редактором:
    -- verified остаётся FALSE, пока автора не сверили с подтверждением учёбы.
    CREATE TABLE IF NOT EXISTS university_reviews (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      university_id BIGINT NOT NULL REFERENCES universities(id) ON DELETE CASCADE,
      user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
      author_name TEXT NOT NULL DEFAULT '',
      author_status TEXT NOT NULL DEFAULT 'student',
      rating NUMERIC NOT NULL CHECK (rating >= 1 AND rating <= 10),
      body TEXT NOT NULL,
      verified BOOLEAN NOT NULL DEFAULT FALSE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX IF NOT EXISTS universities_region_idx ON universities(region);
    CREATE INDEX IF NOT EXISTS applications_university_idx ON applications(university_id);
    CREATE INDEX IF NOT EXISTS university_reviews_verified_idx ON university_reviews(university_id) WHERE verified;
  `)
}

export const closeDb = async () => {
  if (pool) await pool.end()
}
