import 'dotenv/config'
import pg from 'pg'

const { Pool } = pg
let pool

const getPool = () => {
  if (pool) return pool
  const connectionString = process.env.DATABASE_URL
  if (!connectionString) {
    throw new Error('DATABASE_URL is required. Add it to .env locally or connect a Render PostgreSQL database.')
  }

  const isLocalPostgres = /@(localhost|127\.0\.0\.1)(:|\/)/.test(connectionString)
  pool = new Pool({
    connectionString,
    max: 5,
    ssl: process.env.PGSSLMODE === 'require' || (!isLocalPostgres && process.env.NODE_ENV === 'production')
      ? { rejectUnauthorized: false }
      : undefined,
  })
  return pool
}

export const query = (sql, params = []) => getPool().query(sql, params)

export const withTransaction = async (work) => {
  const client = await getPool().connect()
  try {
    await client.query('BEGIN')
    const result = await work(client)
    await client.query('COMMIT')
    return result
  } catch (error) {
    await client.query('ROLLBACK')
    throw error
  } finally {
    client.release()
  }
}

export const initDb = async () => {
  await query(`
    CREATE TABLE IF NOT EXISTS agencies (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL UNIQUE,
      email TEXT NOT NULL,
      phone TEXT,
      website TEXT,
      description TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS universities (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL UNIQUE,
      city TEXT NOT NULL,
      city_safety TEXT NOT NULL DEFAULT 'not_rated',
      city_safety_description TEXT NOT NULL DEFAULT '',
      region TEXT NOT NULL,
      ranking INTEGER,
      specialties TEXT NOT NULL DEFAULT '',
      requirements TEXT NOT NULL DEFAULT '',
      tuition TEXT NOT NULL DEFAULT '',
      description TEXT NOT NULL DEFAULT '',
      website TEXT,
      source_url TEXT,
      verified_at DATE,
      name_translations JSONB NOT NULL DEFAULT '{}'::jsonb,
      description_translations JSONB NOT NULL DEFAULT '{}'::jsonb,
      specialties_translations JSONB NOT NULL DEFAULT '{}'::jsonb,
      requirements_translations JSONB NOT NULL DEFAULT '{}'::jsonb,
      tuition_translations JSONB NOT NULL DEFAULT '{}'::jsonb,
      image_url TEXT,
      image_source TEXT,
      image_gallery JSONB NOT NULL DEFAULT '[]'::jsonb,
      data_status TEXT NOT NULL DEFAULT 'requires_verification',
      data_checked_at DATE,
      agency_id BIGINT REFERENCES agencies(id),
      students_count INTEGER NOT NULL DEFAULT 0
    );

    ALTER TABLE universities ADD COLUMN IF NOT EXISTS name_translations JSONB NOT NULL DEFAULT '{}'::jsonb;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS city_safety TEXT NOT NULL DEFAULT 'not_rated';
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS city_safety_description TEXT NOT NULL DEFAULT '';
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS description_translations JSONB NOT NULL DEFAULT '{}'::jsonb;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS specialties_translations JSONB NOT NULL DEFAULT '{}'::jsonb;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS requirements_translations JSONB NOT NULL DEFAULT '{}'::jsonb;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS tuition_translations JSONB NOT NULL DEFAULT '{}'::jsonb;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS image_url TEXT;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS image_source TEXT;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS image_gallery JSONB NOT NULL DEFAULT '[]'::jsonb;
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS data_status TEXT NOT NULL DEFAULT 'requires_verification';
    ALTER TABLE universities ADD COLUMN IF NOT EXISTS data_checked_at DATE;

    CREATE TABLE IF NOT EXISTS users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email TEXT NOT NULL UNIQUE,
      password_hash TEXT,
      google_id TEXT UNIQUE,
      full_name TEXT,
      country TEXT,
      phone TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    ALTER TABLE users ADD COLUMN IF NOT EXISTS google_id TEXT;
    ALTER TABLE users ALTER COLUMN password_hash DROP NOT NULL;
    CREATE UNIQUE INDEX IF NOT EXISTS users_google_id_idx ON users(google_id) WHERE google_id IS NOT NULL;

    CREATE TABLE IF NOT EXISTS auth_sessions (
      token_hash TEXT PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      expires_at TIMESTAMPTZ NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE INDEX IF NOT EXISTS auth_sessions_expires_idx ON auth_sessions(expires_at);

    CREATE TABLE IF NOT EXISTS applications (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES users(id),
      university_id BIGINT NOT NULL REFERENCES universities(id),
      status TEXT NOT NULL DEFAULT 'pending',
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      UNIQUE (user_id, university_id)
    );

    CREATE INDEX IF NOT EXISTS universities_region_idx ON universities(region);
    CREATE INDEX IF NOT EXISTS applications_university_idx ON applications(university_id);
  `)
}

export const closeDb = async () => {
  if (pool) await pool.end()
}
