services:
- type: web
  name: studichan
  runtime: node
  region: singapore
  plan: free
  buildCommand: npm ci && npm run build
  startCommand: npm start
  initialDeployHook: npm run db:seed
  healthCheckPath: /api/health
  envVars:
    - key: NODE_ENV
      value: production
    - key: DATABASE_URL
      fromDatabase:
        name: studichan-db
        property: connectionString

databases:
  - name: studichan-db
    databaseName: studichan
    user: studichan
    region: singapore
    plan: free